# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 09:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date organized'),
        ),
    ]
