# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0002_trip_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='latlong',
        ),
        migrations.AddField(
            model_name='meetup',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='location',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='name',
            field=models.TextField(blank=True, verbose_name='Name'),
        ),
    ]
