# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0003_auto_20171201_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('CAN', 'Cancelled'), ('ENR', 'En Route')], default='ACT', max_length=3),
        ),
    ]
