# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0004_trip_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
    ]
