# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0005_taxicompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=15, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='latitude',
            field=models.FloatField(blank=True, default=41.8415321, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='longitude',
            field=models.FloatField(blank=True, default=140.7668693, null=True, verbose_name='Longitude'),
        ),
    ]
