# Generated by Django 2.0 on 2019-10-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0006_auto_20171206_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='email',
            field=models.CharField(default='default@sumilab.org', max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='latitude',
            field=models.FloatField(blank=True, default=41.8415321, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='trip',
            name='longitude',
            field=models.FloatField(blank=True, default=140.7668693, null=True, verbose_name='Longitude'),
        ),
    ]
