# Generated by Django 2.0 on 2019-10-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0007_auto_20191025_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='meetup_pt',
        ),
    ]
