# Generated by Django 2.0 on 2019-10-30 07:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0009_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date')),
                ('message', models.CharField(max_length=6000)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(default='default@sumilab.org', max_length=200)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discover.Trip')),
            ],
        ),
    ]
